' PlantUML: tool per la generazione di UML (.png) in modo testuale
' supporta diversi diagrammi UML 
' (es. diagramma delle classi, di sequenza...)
' esempio file class_diagram.puml per generare UML a destra
' download (jar): http://plantuml.com/download
' documentazione: http://plantuml.com/class-diagram
' estensione per VS Code (PlantUML): https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
' (premi ALT-D per aprire la preview in VS Code)

@startuml State

' START STYLE
skinparam {
	'monochrome true
	'shadowing false
	'classBackgroundColor white
	'noteBackgroundColor white
	classAttributeIconSize 0
	'linetype polyline
	'linetype ortho
}
hide circle
' END STYLE

title State

class Client{
    + main(args: String[]): void
}

class Cassa{
    - stato: Stato
    + Cassa()
    + emettiScontrino(prezzo: int): void
    + ricarica(): void
    + ripara(): void
}

class Stato <<interface>>{
    + esegui(s: int): Stato
    + ricarica(): Stato
    + ripara(): Stato
}

class Carico{
    + esegui(s: int): Stato
    + ricarica(): Stato
    + ripata(): Stato
}

class Scarico{
    + esegui(s: int): Stato
    + ricarica(): Stato
    + ripata(): Stato
}

class Inceppato{
    + esegui(s: int): Stato
    + ricarica(): Stato
    + ripata(): Stato
}

' definisco le relazioni
Client -up-> Cassa
Cassa -down-> Stato
Stato <|.down. Carico
Stato <|.down. Scarico
Stato <|.down. Inceppato
@enduml